openapi: 3.0.0
info:
  title: Flight Check-In Step 3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /flights:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                checked-in-passenger:
                  value:
                    barcodeData: s0m3numb3r5
                    checkedInStatus: CHECKED_IN
                    seatNumber: A3
                    seatName: SIDE_BIRTH
                    flightName: AIR_INDIA
                    ticketNum: F2GLK5

              schema:
                $ref: ./reference/models/flight.v1.yaml
